apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-hybrid
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-world-hybrid
        image: registry.redhat.io/rhel10/httpd-24:1790750455
        env:
        - name: MI_ENTORNO
          value: "Desarrollo - OpenShift Cluster"
