apiVersion: v1
kind: Secret
metadata:
  name: repository-gitops-pull
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: GitOps
  url: https://github.com/rofrba/argo-multicluster.git
  type: git
  insecure: 'true'
---