apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bajos-hello-project-app
  namespace: openshift-gitops
spec:
  project: default 
  destination:
    server: https://kubernetes.default.svc # El Spoke despliega 'in-cluster'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true
      prune: false # cambiar por true en produccion
      allowEmpty: true
  source:
    repoURL: 'https://github.com/rofrba/argo-multicluster.git'
    targetRevision: main
    path: 'hybrid/proyectos/hello-project/bajos'
    directory:
      recurse: true
      # Importante: que no intente desplegarse a sí mismo
      exclude: '{bajos-hello-project-app.yaml}'