apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: example 
    annotations:
      argocd.argoproj.io/sync-wave: "1" 
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
    - group: argoproj.io
      kind: ApplicationSet
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: dev-example
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
- apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: example-set 
    annotations:
      argocd.argoproj.io/sync-wave: "1" 
  spec:
    generators:
    - list:
        elements:
        - env: dev
          project: example
    template:
      metadata:
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        name: '{{env}}-{{project}}'
        namespace: openshift-gitops
      spec:
        destination:
          namespace: '{{env}}-{{project}}'
          server: https://kubernetes.default.svc
        project: '{{project}}'
        source:
          directory:
            recurse: true
          path: pull/bajos/proyectos/{{project}}/{{env}}
          repoURL: https://github.com/rofrba/argo-multicluster.git
          targetRevision: main
        syncPolicy:
          automated:
            selfHeal: false
          syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
