apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications-hybrid
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: hybrid/proyectos
    repoURL: 'https://github.com/rofrba/argo-multicluster.git'
    targetRevision: main
  project: openshift-gitops-hybrid
  syncPolicy:
    automated:
      selfHeal: true
      prune: false # cambiar por true en produccion
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      