apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-hello-project-push
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: 'https://github.com/rofrba/argo-multicluster.git'
      revision: main
      files:
      - path: "push/cluster/*/cluster-config.json"
  
  template:
    metadata:
      name: '{{path.basename}}-hello-project'
    spec:
      project: multi-cluster-push
      
      
      source:
        repoURL: 'https://github.com/rofrba/argo-multicluster.git'
        targetRevision: main
        
        # Construye la ruta: "proyectos/spoke-apps/ris-philips/dev"
        path: 'push/proyectos/hello-project/{{path.basename}}'
        
        directory:
          recurse: true 
      
      destination:
        name: '{{name}}' # 'name' viene del cluster-config.json
        namespace: openshift-gitops
      
      syncPolicy:
        automated:
          selfHeal: true
          prune: false # cambiar por true en produccion
          allowEmpty: true