apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: prod-hello-service-app
    namespace: openshift-gitops 
    annotations:
      argocd.argoproj.io/sync-wave: "1" 
  spec:
    destination:
      namespace: prod-example
      server: https://kubernetes.default.svc
    project: prod-example
    source:
      path: manifests/hello-world/overlays/prod
      repoURL: https://github.com/rofrba/argo-multicluster.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
