apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../../base-hybrid
kind: Kustomization
namespace: dev-example-hybrid
patches:
- path: ./deployment-patches.yaml
  target:
    kind: Deployment
    name: hello-world-hybrid
