apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello-world
        image: registry.redhat.io/rhel10/httpd-24:1790750455
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -e "s|VALUE_MI_ENTORNO|${MI_ENTORNO}|g" \
                -e "s|VALUE_MI_MODELO|${MI_MODELO}|g" \
                -e "s|VALUE_MI_COLOR|${MI_COLOR}|g" \
                -e "s|VALUE_POD|${HOSTNAME}|g" \
                /tmp/template/index.html > /var/www/html/index.html && \
            exec container-entrypoint run-httpd
        envFrom:
        - configMapRef:
            name: app-config   # Kustomize le agrega el hash automáticamente
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: html-template-volume
          mountPath: /tmp/template
        - name: www-html-volume
          mountPath: /var/www/html
      volumes:
      - name: html-template-volume
        configMap:
          name: html-template
      - name: www-html-volume
        emptyDir: {}
