apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-project-prod-hybrid
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: "Proyecto para las aplicaciones de hello-project en el entorno prod"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'