apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: bajos-hello-world-app
    namespace: openshift-gitops 
    annotations:
      argocd.argoproj.io/sync-wave: "1" 
  spec:
    destination:
      namespace: dev-example-hybrid
      server: https://kubernetes.default.svc
    project: hello-project-bajos-hybrid
    source:
      path: manifests/hello-world/overlays/bajos/hybrid
      repoURL: https://github.com/rofrba/argo-multicluster.git
      targetRevision: main
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}
