apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../../base
kind: Kustomization
namespace: prod-example-push
patches:
- path: ./deployment-patches.yaml
  target:
    kind: Deployment
    name: hello-world
