apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../../base-push
kind: Kustomization
namespace: dev-example-pull
patches:
- path: ./deployment-patches.yaml
  target:
    kind: Deployment
    name: hello-world-push
