apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# entorno + modelo = lo que despliega Argo CD
namespace: kcd-hybrid-prod

resources:
- ../../../envs/prod

components:
- ../../../components/hybrid
